name: Test Action

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

env:
  BUILD_TYPE: core
  DEFAULT_PYTHON: 3.8

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    steps:
      - name: Build Meta Image
        shell: bash
        env:
          VCN_ORG: ${{ secrets.VCN_ORG }}
        run: |
          function sto_cazzo {

            if [[ "$VCN_ORG" =~ ^0x ]]; then
              vcn_cli="--signerID"
            else
              vcn_cli="--org" 
            fi

            echo ("${vcn_cli}" "$VCN_ORG")
          }

          sto_cazzo